name: Générer actus.json

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install node-fetch@2
      - name: Lancer le script de récupération
        run: node fetch-news.js
      - name: Commit & Push actus.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add actus.json
          git commit -m "Mise à jour automatique actus.json" || echo "Pas de changement"
          git push
